CREATE DATABASE CRUD;

CREATE TABLE VAGAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(50),
    DESCRICAO TEXT,
    ATIVO ENUM('S','N'),
    DATA DATETIME
)ENGINE=INNODB;

CREATE TABLE USUARIO 
(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USUARIO VARCHAR (30) NOT NULL,
    SENHA VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL
    IP VARCHAR (30),
    DATA_CADASTRO DATETIME
)ENGINE=INNODB;


CREATE TABLE USUARIO_TERMO
(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_TERMO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    DATA_ASSINATURA DATETIME

)ENGINE=INNODB;


CREATE TABLE TERMO_USO
(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TERMO TEXT,
    VERSAO VARCHAR(20),
    DATA_VERSAO DATETIME
)ENGINE=INNODB


ALTER TABLE usuario_termo
ADD CONSTRAINT FK_id_termo
FOREIGN KEY (ID_TERMO) REFERENCES termo_uso(ID) ON DELETE CASCADE;

ALTER TABLE usuario_termo
ADD CONSTRAINT FK_id_usuario
FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID) ON DELETE CASCADE;

